/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package C_Excepciones.A_Acertijo;

import java.util.Calendar;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Ignacio
 */
public class VentanaAcertijo extends javax.swing.JFrame {

    long iniMilisegundos;
    int intentos = 0;
    int numAleatorio;
    Random generadorNum = new Random();    

    public VentanaAcertijo() {
        initComponents();

        //Centramos la ventana
        setLocationRelativeTo(null);
    }

    private int generaAleatorio(){
        return generadorNum.nextInt(100)+1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFIntentos = new javax.swing.JTextField();
        jBJugar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTFTiempo = new javax.swing.JTextField();
        jBValidar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acertijo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("ACERTIJO");

        jLabel2.setText("Introduzca un Número del 1 al 100:");

        jTFNumero.setEnabled(false);

        jLabel3.setText("Número de Intentos:");

        jTFIntentos.setEditable(false);

        jBJugar.setText("Iniciar Juego");
        jBJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBJugarActionPerformed(evt);
            }
        });

        jLabel4.setText("Tiempo");

        jTFTiempo.setEditable(false);

        jBValidar.setText("Validar");
        jBValidar.setEnabled(false);
        jBValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBValidar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBJugar))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jBJugar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBValidar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTFTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBJugarActionPerformed
        
        //Activamos el Texto para Introducir Numeros
        jTFNumero.setEnabled(true);
        jBValidar.setEnabled(true);
        
        //Obtenemos el Tiempo Actual en Milisegundos
        Calendar rightNow = Calendar.getInstance();
        iniMilisegundos = rightNow.getTimeInMillis();
        System.out.println("Segundos Iniciales: " + iniMilisegundos);
        
        //Obtenemos el Numero Aleatorio
        numAleatorio = generaAleatorio();
    }//GEN-LAST:event_jBJugarActionPerformed

    private void jBValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBValidarActionPerformed
        
        try {
            int numero = Integer.valueOf(jTFNumero.getText());
            validaNumero(numero);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                        this,
                        "Debe introducir un Número",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);

            jTFNumero.setText("");
        } finally {
            //Incrementamos el Numero de Intentos
            intentos++;
            jTFIntentos.setText(""+intentos);
        }
    }//GEN-LAST:event_jBValidarActionPerformed

    private void validaNumero(int numero){
        if (numero > numAleatorio){
            JOptionPane.showMessageDialog(
                        this,
                        "Introduzca un numero Menor",
                        "Mayor",
                        JOptionPane.INFORMATION_MESSAGE);
        }else if (numero < numAleatorio){
            JOptionPane.showMessageDialog(
                        this,
                        "Introduzca un numero Mayor",
                        "Menor",
                        JOptionPane.INFORMATION_MESSAGE);
        }else{
            acertijoAcertado();
        }            
    }
    
    private void acertijoAcertado(){
        JOptionPane.showMessageDialog(
                this,
                "Ha acertado el Número",
                "Correcto",
                JOptionPane.INFORMATION_MESSAGE);

        jTFNumero.setEnabled(false);
        jBValidar.setEnabled(false);
        
        //Obtenemos el Tiempo Actual en Milisegundos
        Calendar rightNow = Calendar.getInstance();
        long finMilisegundos  = rightNow.getTimeInMillis();
        System.out.println("Segundos Finales: " + finMilisegundos);
        
        //Calculamos el Tiempo total
        long segTotales = (finMilisegundos  - iniMilisegundos) / 1000;        
        jTFTiempo.setText(""+segTotales);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAcertijo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAcertijo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAcertijo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAcertijo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAcertijo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBJugar;
    private javax.swing.JButton jBValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTFIntentos;
    private javax.swing.JTextField jTFNumero;
    private javax.swing.JTextField jTFTiempo;
    // End of variables declaration//GEN-END:variables
}
