/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package B_Bucles.F_Elecciones;

import java.util.Random;

/**
 *
 * @author Ignacio
 */
public class VentanaElecciones extends javax.swing.JFrame {

    final int MIN_PARTIDOS  = 4;
    final int MAX_PARTIDOS  = 10;
    final int MAX_VOTOS = 10;
    int matrizPartidos[];
    int numPartidos = MIN_PARTIDOS;
            
    /**
     * Creates new form VentanaElecciones
     */
    public VentanaElecciones() {
        initComponents();
        inicializaVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFNumPartidos = new javax.swing.JTextField();
        jBMas = new javax.swing.JButton();
        jBMenos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAResultado = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ELECCIONES MUNICIPALES");

        jLabel2.setText("Número de Partidos:");

        jTFNumPartidos.setEditable(false);
        jTFNumPartidos.setText("4");

        jBMas.setText("+");
        jBMas.setAlignmentY(0.0F);
        jBMas.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMasActionPerformed(evt);
            }
        });

        jBMenos.setText("-");
        jBMenos.setAlignmentY(0.0F);
        jBMenos.setEnabled(false);
        jBMenos.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMenosActionPerformed(evt);
            }
        });

        jButton1.setText("Iniciar Elecciones");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTAResultado.setColumns(20);
        jTAResultado.setRows(5);
        jScrollPane1.setViewportView(jTAResultado);

        jLabel3.setText("Resultado Elecciones:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFNumPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBMas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFNumPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMas)
                    .addComponent(jBMenos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMasActionPerformed
        
        numPartidos = Integer.valueOf(jTFNumPartidos.getText());

        if (numPartidos < MAX_PARTIDOS) {
            numPartidos++;
            jTFNumPartidos.setText(""+numPartidos);
        }
        //Activa o Desactiva los Botones Mas o Menos
        validaBotones();
    }//GEN-LAST:event_jBMasActionPerformed

    private void jBMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMenosActionPerformed

        numPartidos = Integer.valueOf(jTFNumPartidos.getText());

        if (numPartidos > MIN_PARTIDOS) {
            numPartidos--;
            jTFNumPartidos.setText(""+numPartidos);
        }
        //Activa o Desactiva los Botones Mas o Menos
        validaBotones();
    }//GEN-LAST:event_jBMenosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        inicializaTextoResultados();
        generaVotos();
        imprimeResultados();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inicializaTextoResultados(){
        jTAResultado.setText("RESULTADO DE LAS ELECCIONES\n");
        jTAResultado.append("--------------------------------------------------\n");
    }
    
    private void validaBotones(){
        if (numPartidos >= MAX_PARTIDOS) {
            jBMas.setEnabled(false);
        } else {
            jBMas.setEnabled(true);
        }

        if (numPartidos <= MIN_PARTIDOS) {
            jBMenos.setEnabled(false);
        } else {
            jBMenos.setEnabled(true);
        }
    }
    
    private void inicializaVentana(){
        jTFNumPartidos.setText(""+MIN_PARTIDOS);
        jBMenos.setEnabled(false);
        jBMas.setEnabled(true);
        jTFNumPartidos.setEditable(false);
        jTFNumPartidos.setEnabled(true);
    }
    
    private void generaVotos(){
        
        Random generadorNum = new Random();
        matrizPartidos = new int[numPartidos];
        int votoAleatorio;
        boolean ganador = false;
        
        do{
            votoAleatorio = generadorNum.nextInt(numPartidos);
            matrizPartidos[votoAleatorio]= matrizPartidos[votoAleatorio] + 1;
            
            //Si el Parido que ha sido votado tiene 1000 votos
            if (matrizPartidos[votoAleatorio] == MAX_VOTOS)
                ganador = true;            
        } while (!ganador);
        
        //Mensaje con el Ganador de las Elecciones
        jTAResultado.append("EL PARTIDO GANADOR ES EL "+(votoAleatorio + 1)+"\n");
    }
    
    private void imprimeResultados(){
        
        //Ponemos una Linea Separadora
        jTAResultado.append("--------------------------------------------------\n");
        
        //Imprimimos los Resultados
        for (int x=0; x<numPartidos;x++){
            jTAResultado.append("El Partido: "+(x+1)+" ha obtenido: "+ matrizPartidos[x] + " votos\n");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaElecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaElecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaElecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaElecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaElecciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBMas;
    private javax.swing.JButton jBMenos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAResultado;
    private javax.swing.JTextField jTFNumPartidos;
    // End of variables declaration//GEN-END:variables
}
